# Check https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/ for more details
# Deprecated in v1.16 in favor of apiextensions.k8s.io/v1
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: containerruntimes.alexpetrescu.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: alexpetrescu.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: containerruntimes
    # singular name to be used as an alias on the CLI and for display
    singular: containerruntime
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: ContainerRuntime
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - ctr
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
              # image for the pods that our deployment is creating
              image:
                type: string
              # the port that our pods are exposing; this pis the port that our service is exposing internally (port)
              containerPort:
                type: number
              # replication factor for our deployment
              replicas:
                type: number
