apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-container
  labels:
    app: nginx-container
spec:
  selector:
    matchLabels:
      app: nginx-container
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-container
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14.2
        ports:
        - containerPort: 80
