apiVersion: v1
kind: Service
metadata:
  name: nginx-container
  labels:
    app: nginx-container
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: default-port
  selector:
    app: nginx
